### ISSUE TITLE
Need a Gopher hiding being bansai tree logo

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/bonzai#1]

**Comment by cyrinux** [comment]
Hi Rob,
Feel free to use this 🌳 
![bonzai](https://user-images.githubusercontent.com/519083/160919215-6dce1032-2968-4c3e-ba88-22fe8ea22353.png)
![bonzai](https://user-images.githubusercontent.com/519083/160919236-47e49233-bfef-4cd9-8a15-45c31d02d193.svg)
