### ISSUE TITLE
bonzai does not work when pyenv in $PATH

### ISSUE THREAD

**Issue by blob42** [rwxrob/bonzai#109]
Hi, thanks for your work and streams. Bonzai is an excellent idea and I am planning to move my scritps as well to it after I understand how to use it. 

I have pyenv on my environment, running any bonzai command that calls a help command fails with `pyenv: no such command "tmp/hlpe-XXXXX"`

If I remove pyenv from my $PATH bonzai help command works. Why would the pyenv executable be called ? I never encountered this issue. 

Is there a way to traceback command exection ? I am willing to fix it if I can the debug the call. `strace` was not  helpfulp.

It should be easy to reproduce by just installing pyenv. The bug happen under any shell (bash, zsh, fish ...) 

Thanks.

**Comment by rwxrob** [comment]
There is nothing directly related to `pyenv` anywhere. The pager will look for a pager in the environment, perhaps that is affecting it. If you could provide the OS you are using and perhaps a recreation of code that produces the error I can help get into it.

**Comment by blob42** [comment]
Just an update that the problem seems resolved for me now. I have no idea what was the issue. If the problem happens again I will investigate. 

Thanks a lot for this project.
