### ISSUE TITLE
Where to find the Bonzai book ?

### ISSUE THREAD

**Issue by craph** [rwxrob/bonzai#120]
Hi,

I'm trying to find the Bonzai book to learn how it works and how to use it correctly.
Is the any website for documentation or book to explain all this ?
In the README.md file of the repository, there is this link : https://github.com/rwxrob/book-bonzai but this is a 404 page on github.

Thank you very much for your help.
Best regards,

**Comment by rwxrob** [comment]
No book yet. We have decided to put that effort into the package documentation itself instead. For now look into the `cmds` package for several examples and learn from them.
