### ISSUE TITLE
Error text for ErrInvalidShort is confusing

### ISSUE THREAD

**Issue by markjuh** [rwxrob/bonzai#260]
Because of #227 `ErrInvalidShort` is not only used for checking the length of `Short`, but also for checking if the `Short` starts with a lower case character.

I had this:
```
Short: `Command tree`,
```

And then you get this confusing error:
```
2024/11/17 12:41:19 Short length >50 or not lower for "z": "Command tree"
```

It was not very clear that the `or not lower` was about the first character. And that is should be lower case.

Commands further in the tree can have a `Short` that starts with an upper case character or that is longer than 50 characters. Is that intentional?

**Comment by rwxrob** [comment]
They cannot but the bug isn't hit it is used. Only the top and leaf are checked currently. Now that we return an error on SeekInit we might be able to check all.
