### ISSUE TITLE
Need a template tag to add the path in the long description.

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rwxrob/bonzai#262]
I'm writing examples in the Long description field and wanted to have a template to add the path to the current cmd from the top of the tree. This prevents me from writing only the cmd name and confusing the users reading the help.

**Comment by rwxrob** [comment]
Do you want dots, dashes, or just an array? There is already `{{ .Path }}` but that might not be what is wanted. I'm thinking of adding a generic `{{ dotted .Path }}` so that any slice can be joined. But `{{ path . }}` would be the most succinct.
