### ISSUE TITLE
There should be a unified interface for declaring vars and env for a command.

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rwxrob/bonzai#270]
This unified interface should also be used for completion of keys of vars. This should also populate the help documentation as `Variables` and `Environment` sections.

Currently having two fields to set field that are semantically the same but are just named differently is repetitive. Also there is no point of it apart from  it being documented "with" the command. For e.g. kimono has all these "constants" at the package level and that is what is being used in the Do func callback as well. There is no point to use the `Cmd.Env` or `Cmd.Var` fields when you have direct access to the constants. 

The solution I suggest is to expand the bonzai.Var struct to have an optional `env` field which will share the same defaults/values as the Var. When adding it to the environment, the values can be stringified, if possible. All errors in "string-ification" should be the responsibility of the user of the library.

**Comment by rwxrob** [comment]
I agree fully with this. I'll remove Env for now. What do you think should be added to the Var? `Env string` perhaps for the Env name to optionally look up? Or perhaps a boolean.

**Comment by Chaitanyabsprip** [comment]
an `Env` string so that vars doesn't need to follow the all caps std format for env names.

**Comment by Chaitanyabsprip** [comment]
also I watched the vod related to the discussion after I mentioned this issue. Regarding what vars should be persisted, I think we should another `persist` field such that it can be looked up by the vars.Cmd to persist.

**Comment by Chaitanyabsprip** [comment]
Instead of Cmd.Vars being a map[string]Var it should be a []Var and the map should be maintained as a private variable in the Cmd struct. This warrants another method to fetch the Var with the key. This approach reduces redundancy of doing `{ KEY: Var{ Key: KEY } }`.
