### ISSUE TITLE
Add bonzai.Persistence and Persister with CmdCompletion

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/bonzai#275]
By moving the vars.Driver interface definition and adding Complete method into bonzai itself the Set/Get methods can do the work of `var` without requiring the var command to be imported.

**Comment by Chaitanyabsprip** [comment]
I saw the PR, even though you'll have the interface and package level variable for the `Persister`, you will have to import vars in anyway for the default driver, no?

To set the `Persister` in the user bonzai Cmd files, we'd have to add init methods, which is not as sleek as using the `vars.Cmd`.

We can't have the default implementation in bonzai because that pulls in a bunch of dependencies and also you can't use the default implementation (from bonzai) in vars because that will cause a circular dependency.

**Comment by rwxrob** [comment]
The problem is Var.Persist. People expect it to automatically persist when set and Cmd.Set is called. The alternative is to call both Set *and also* something that implements persistence that is not necessarily consistent for everything in the binary. This seems like way more code than just an `init()` assigning to `bonzai.Persistence` or better, something like this:

```go
func main() {
  bonzai.Persistence = vars.Driver
  foo.Cmd.Run()
}
```

Or maybe a bit of syntactical sugar:

```go
func main() {
  foo.Cmd.WithPersistence(vars.Driver).Run()
}
```

The `var` command will still be needed, but it will probably be a `vars.Editor` interface that embeds `bonzai.Persistence` interface adding more methods for dealing with bulk editing.

Thoughts?

**Comment by rwxrob** [comment]
Another thing is that `comp.Vars` can be implemented to use to complete var keys with different scopes, the current Cmd, or perhaps all the Cmds above it as well. We can keep `vars.Comp` to use completion against the entire set of persistent keys for the given binary, which may or may not all be declared with Vars.

There's another implicit design question here. Should we mandate declaration of any and all variables used in Vars now? This seems reasonable now that we have a comprehensive way of handling them. It would mean that bonzai command creators follow the same convention for such things that can be relied upon. A command that uses a variable from some other external source then becomes less than best practice unless there is data that must live outside of the Vars space. Opening external application configuration files and such is probably one solid example of this. 

I do wish we could tackle the abstraction of conventional configuration with standardization on the yq/jq dialect so that I can port certain applications into a universal collection of configuration files. But that is another project. I had that before. Cobra has Viper to attempt this, but it has not been adopted at all, probably because it is lacking the yq/jq dialect. We could specify a `bonzai.Configuration` implementation like `bonzai.Persistence` but rather than being key-value pairs it would have a specific configuration name. (We can talk about all this later.)

**Comment by rwxrob** [comment]
Also, what about Var.Export? Now that all declared Cmd.Vars are cached privately, we can block their retrieval in Get/Set to different scopes:

- Only the current Cmd in which Vars was declared
- Only the immediate childen of Cmd (Cmd.Cmds and Cmd.Def)
- All descendents in the Leaf.Path

This actually addresses a concern about security that I had before. A branch can be grafted in from an unknown source and even after compilation cannot mess with another Cmds declared Vars if the Cmd author does not want.

**Comment by Chaitanyabsprip** [comment]
I like the scope idea, that is something you cannot have with package level variables.

**Comment by rwxrob** [comment]
The scope thing also allows us to automatically document Vars based on scope and inheritance stuff.

**Comment by Chaitanyabsprip** [comment]
I get your point about having to call both the Set(Cmd and vars.Driver) methods. That becomes inevitable. Also, I already thought that Cmd.Vars will now be the "idiomatic" way of handling variables for Cmds.

**Comment by Chaitanyabsprip** [comment]
Are we going to allow separate persistence drivers per Cmd? You example of `foo.Cmd.WithPersistence(vars.Data)` hints towards that. One use case I can think of is to isolate a data heavy operation Cmd (reads from Database or remote) vs a usual operation Cmd (reads from a configuration file). You wouldn't want all your configuration to be in a full blown database when a conf file will suffice. I'm not sure whether the isolation of packages will allow one persistence driver per command.

**Comment by Chaitanyabsprip** [comment]
Allowing that would also require us to have good defaults. If it's not set in all node Cmds of a tree then should it assume the Driver of the parent Cmd?

**Comment by rwxrob** [comment]
I'm trying to get back into this and realizing the complexity is high going into it to simplify everything for those using Bonzai later. The single biggest question relates to allowing a Cmd to have its own persistence driver, which might be at odds with the whole scope thing. I think we need some use cases to clarify this:

```
cmd
  subcmd
    subsubcmd
```

I think something like the following scopes are needed:

- self - just self
- internal - self and anything below
- public - anything above or below

We still have the question of allowing family to override the values of the parents if they have the same key names. This is like shadowing. I can think of a number of powerful uses for this during debugging of children of something that has its own complex persister. A simpler persister for debugging could be put below it to shadow and respond to the propagated Get and Set calls.

I feel like there is another Var property, maybe Auth. Something that tells the Get Set propagator that this thing is authoritative and cannot be shadowed causing the bonzai equiv of a panic. Maybe this is overkill though. It would create situations where an independent internal cmd couldn't function at all because something above decided to squat on the key name. I think that is up to the develop composing the things together to be sure of that. The use case for shadowing is way more compelling.

Besides, we will never be able to absolutely prevent a subcommand from referring to the variables of one of its parents by looking it up directly so long as we use Cmd.Vars instead of some method alternative. But we can make `Get` and `Set` aware of the scope. I feel like that balance is a good thing when cobbling together command trees that are the intent here. Kind of Python/JS-esque but with stricter type checking in Get/Set.

But now what do we do about custom persistence?

I think that `cmd.WithPersister()` works best because it can internally cache a `Cmd.persister` and if set just use that. There would never be a way to retrieve it, only use it indirectly with Get and Set.

The problem of default persister is another big one. I think the safest thing is to have a package that provides the driver automatically when imported. So `vars.Cmd`, for example, could automatically change the `bonzai.Persister` package if not set in its `init()`. I do feel like that is a lot of magic that would burn people. I'm inclined to force `main` authors to explicitly assign it.

It is going to be important not to mix up `WithPersister()` and `bonzai.Persister`.

**Comment by rwxrob** [comment]
I feel like trying to set an undeclared variable should panic. It is one of the few cases and even though the panic will be trapped it signals to the developer that it is being used in a bad way. Silently ignoring isn't loud enough and could lead to confusion.

**Comment by rwxrob** [comment]
Need to remember to add a goroutine test with Vars to be sure they are safe for concurrency.

**Comment by rwxrob** [comment]
The implementation of Var.I for inherited Vars with Ref pointing to a resolved, inherited value presents a problem when considering the possibility of resolving to another inherited value. This alleviated by the fact that only K values are considered during the traversal up the SeekInit path to root command.

**Comment by rwxrob** [comment]
Got it into the last PR.
